### ISSUE TITLE
Acho que mandei um pullrequest sem querer

### ISSUE THREAD

**Issue by SaMatheus** [DevMagic/frontend-intern-challenge#38]
Olá.
Acho que mandei um pullrequest sem querer.
Se foi mesmo, desconsidera, por favor, ainda não finalizei o teste hehehe

Desculpe ai.

**Comment by biliboss** [comment]
Sem problemas. Quando finalizar, não esqueça de enviar a resposta pelo link que foi no 1° e-mail.
